# This Docker Compose file was built solely for development purposes.

version: "3"
services:
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    networks:
      - pgsql-network
    # volumes:
    #   - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5433:80"
    depends_on:
      - postgresql
    networks:
      - pgsql-network

# volumes:
#   db-data:

networks:
  pgsql-network:
    driver: bridge
